# Suggested filename: .github/workflows/dkml.yml

name: Build with DkML compiler

on:
  push:
    branches:
      - main
      - v*
    tags:
      - v*
  # ... or trigger manually from GitHub web interface
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86
            dkml_host_abi: windows_x86
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86_64
            dkml_host_abi: windows_x86_64
          - gh_os: ubuntu-latest
            abi_pattern: manylinux2014-linux_x86
            dkml_host_abi: linux_x86
          - gh_os: ubuntu-latest
            abi_pattern: manylinux2014-linux_x86_64
            dkml_host_abi: linux_x86_64
          - gh_os: macos-latest
            abi_pattern: macos-darwin_all
            dkml_host_abi: darwin_x86_64

    runs-on: ${{ matrix.gh_os }}
    name: build / ${{ matrix.abi_pattern }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Checkout DkML compilers on a Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        shell: msys2 {0}
        run: ./dk dkml.workflow.compilers PRERELEASE CI GitHub OS Windows

      - name: Checkout DkML compilers on a non-Windows host
        if: "!startsWith(matrix.dkml_host_abi, 'windows_')"
        run: ./dk dkml.workflow.compilers PRERELEASE CI GitHub

      # The .ci/dkml-compilers "pre" actions will create the environment variables:
      #   opam_root, exe_ext, dkml_host_abi, abi_pattern (and many more)

      - name: Setup DkML compilers on a Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        uses: .ci/dkml-compilers/gh-windows/pre
        with:
          DKML_COMPILER: ${{ env.DKML_COMPILER }}

      - name: Setup DkML compilers on a Darwin host
        if: startsWith(matrix.dkml_host_abi, 'darwin_')
        uses: .ci/dkml-compilers/gh-darwin/pre
        with:
          DKML_COMPILER: ${{ env.DKML_COMPILER }}

      - name: Setup DkML compilers on a Linux host
        if: startsWith(matrix.dkml_host_abi, 'linux_')
        uses: .ci/dkml-compilers/gh-linux/pre
        with:
          DKML_COMPILER: ${{ env.DKML_COMPILER }}

      # This section is for your own build logic which you should place in ci/build-test.sh or a similar file

      - name: Build and test on Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        shell: msys2 {0}
        run: ci/build-test.sh

      - name: Build and test on non-Windows host
        if: "!startsWith(matrix.dkml_host_abi, 'windows_')"
        run: ci/build-test.sh

      # The .ci/dkml-compilers "post" actions will finalize caching, etc.

      - name: Teardown DkML compilers on a Windows host
        if: startsWith(matrix.dkml_host_abi, 'windows_')
        uses: .ci/dkml-compilers/gh-windows/post

      - name: Teardown DkML compilers on a Darwin host
        if: startsWith(matrix.dkml_host_abi, 'darwin_')
        uses: .ci/dkml-compilers/gh-darwin/post

      - name: Teardown DkML compilers on a Linux host
        if: startsWith(matrix.dkml_host_abi, 'linux_')
        uses: .ci/dkml-compilers/gh-linux/post
