name: Publish GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed for peaceiris/actions-gh-pages@v3
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OCaml 4.12.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
          dune-cache: false # true does not publish pages consistently
          opam-pin: true
          opam-depext: false # will complain that diskuvbox is missing
      - name: Add Opam pins
        # opam pin dkml-component-network-ocamlcompiler 'https://github.com/diskuv/dkml-component-ocamlcompiler.git#main' --no-action --yes
        # opam pin dkml-component-staging-ocamlrun      'https://github.com/diskuv/dkml-component-ocamlcompiler.git#main' --no-action --yes
        # opam pin dkml-install                         'https://github.com/diskuv/dkml-install-api.git#main' --no-action --yes
        # opam pin dkml-install-runner                  'https://github.com/diskuv/dkml-install-api.git#main' --no-action --yes
        # opam pin dkml-package-console                 'https://github.com/diskuv/dkml-install-api.git#main' --no-action --yes
        # opam pin dkml-component-staging-curl          'https://github.com/diskuv/dkml-component-curl.git#main' --no-action --yes
        # opam pin dkml-installer-network-ocaml         'https://github.com/diskuv/dkml-installer-ocaml.git#main' --no-action --yes
        # opam pin dkml-component-staging-unixutils     'https://github.com/diskuv/dkml-component-unixutils.git#main' --no-action --yes
        # opam pin dkml-component-network-unixutils     'https://github.com/diskuv/dkml-component-unixutils.git#main' --no-action --yes
        # opam pin dkml-component-xx-console            'https://github.com/diskuv/dkml-component-console.git#main' --no-action --yes
        run: |
          opam pin dkml-base-compiler                   'https://github.com/diskuv/dkml-compiler.git#main' --no-action --yes
          opam pin ocaml                                'https://github.com/diskuv/dkml-compiler.git#main' --no-action --yes
          opam pin ocaml-config                         'https://github.com/diskuv/dkml-compiler.git#main' --no-action --yes
          opam pin conf-dkml-cross-toolchain            'https://github.com/diskuv/conf-dkml-cross-toolchain.git#main' --no-action --yes
          opam pin dkml-component-xx-console            'https://github.com/diskuv/dkml-component-console.git#main' --no-action --yes
          opam pin diskuvbox                            'https://github.com/diskuv/diskuvbox.git#main' --no-action --yes
      - name: Install Opam dependencies
        run: opam install . --deps-only --with-doc

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if contributors/environment.yml
          # has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('contributors/environment.yml') }}
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          python-version: 3.7
          environment-file: contributors/environment.yml
          auto-activate-base: false
          activate-environment: sphinx-env
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install graphviz
        run: sudo apt install graphviz
      - name: Build Sphinx
        shell: bash -l {0}
        run: cd contributors && make publish-prepare-docs

      - name: Build odoc
        run: opam exec -- dune build @doc
      - name: Copy odoc into Sphinx site
        run: |
          cmake -E copy_directory _build/default/_doc/_html contributors/_build/html/odoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./contributors/_build/html
