name: Publish GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed for peaceiris/actions-gh-pages@v3
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OCaml 4.14.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          dune-cache: false # true does not publish pages consistently
          opam-pin: true
          opam-depext: false # will complain that diskuvbox is missing
      - name: Install Opam dependencies
        run: opam install . --deps-only --with-doc

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if contributors/environment-ci.yml
          # has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('contributors/environment-ci.yml') }}
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults
          channel-priority: strict
          python-version: 3.7
          environment-file: contributors/environment-ci.yml
          auto-activate-base: false
          activate-environment: sphinx-env-ci
          auto-update-conda: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install graphviz
        run: sudo apt install graphviz
      - name: Build Sphinx
        shell: bash -l {0}
        run: cd contributors && make publish-prepare-docs

      - name: Build odoc
        run: opam exec -- dune build --release @doc
      - name: Copy odoc into Sphinx site
        run: |
          cmake -E copy_directory _build/default/_doc/_html contributors/_build/html/odoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./contributors/_build/html
